### ISSUE TITLE
SnapRaid gets stuck when launched from Elucidate

### ISSUE THREAD

**Issue by Smurf-IV** [Smurf-IV/Elucidate#31]
Launch "Sync" from Elucidate and after a while it gets stuck in TaskManager with 0% CPU !
![image](https://user-images.githubusercontent.com/2418812/49695644-fee63a00-fb95-11e8-97af-5b2bf5bb9163.png)

**Comment by Smurf-IV** [comment]
**More Info.**. Closing Elucidate allows SnapRaid to continue, so it must be something to do with the console redirect and / or the Logging window

**Comment by waxweazle2001** [comment]
Same Problem here, the Snapraid process runs in the taskmanager but the GUI stucks and no control if he really made the process till the end. Is there any solution since now?

**Comment by Smurf-IV** [comment]
> 
> 
> Same Problem here, the Snapraid process runs in the taskmanager but the GUI stucks and no control if he really made the process till the end. Is there any solution since now?

See the more info above, - Just close Elucidate, I am working on a new version, that goes back to basics to allow testing, then add the new features back in.

**Comment by Smurf-IV** [comment]
Still happening in 19.2.850.9 !!
