### ISSUE TITLE
Allow User to select Krypton Theme

### ISSUE THREAD

**Issue by Smurf-IV** [Smurf-IV/Elucidate#47]
What it says on the tin:
![image](https://user-images.githubusercontent.com/2418812/52913702-9fed2180-32b8-11e9-86e4-991523aaeebc.png)

**Comment by Wagnerp** [comment]
Hi @Smurf-IV 

Just a heads-up, I've developed a much more elegant solution to this, which will come in the March Extended Toolkit update.

**Comment by Wagnerp** [comment]
Hi @Smurf-IV 

The one which will be in the March update will be a temporary solution, as I'm developing a far more sophisticated solution for the April update (see development branch).
