### ISSUE TITLE
When adding Check or Diff to scheduler the Windows scheduler shows Sync in description.

### ISSUE THREAD

**Issue by jakebullet70** [Smurf-IV/Elucidate#58]
From the Elucidate scheduler tab add a Check or Diff. Then check the Windows Scheduler and the description says Sync. The commands to do a Diff or Check are correct it is only the description that is wrong.

**Comment by jakebullet70** [comment]
I have fixed this but I am not sure what good a Diff or Check are as a scheduled item as they seem to leave no log.

**Comment by jakebullet70** [comment]
Just found and fixed the bug for "Diff or Check as a scheduled item as they seem to leave no log."

**Comment by Smurf-IV** [comment]
Thanks

**Comment by Smurf-IV** [comment]
#64
