### ISSUE TITLE
Add option in the scheduler to remove older log files.

### ISSUE THREAD

**Issue by jakebullet70** [Smurf-IV/Elucidate#63]
Maybe a PowerShell script that can be scheduled to remove older log files.

**Comment by Smurf-IV** [comment]
Or just use the default NLog functionality via the Elucidate Command Line options and delete the script usage?

**Comment by jakebullet70** [comment]
Just learning NLog but if that would do it then I say use it.

**Comment by Smurf-IV** [comment]
#64
