### ISSUE TITLE
Recover Files not working ? (win)

### ISSUE THREAD

**Issue by Frederic-LM** [Smurf-IV/Elucidate#68]
Hi, using 019.12.997.12
"Differences" do notice deleted file
but Recover Files => view recoverable Files  
 does not see or recover anything

**Comment by Smurf-IV** [comment]
Thanks for the report, I'll look into it, it's probably a flag that is no different with the different SnapRaid.
Can you tell me what version of SnapRaid you are usingp lease ?

**Comment by Smurf-IV** [comment]
Wow, This shows that there is still quite a lot of code that needs to be re-worked.

**Comment by Smurf-IV** [comment]
Release for this available here:
https://github.com/Smurf-IV/Elucidate/releases/tag/v20.7.1003.4

**Comment by Smurf-IV** [comment]
Please be aware of #70
