### ISSUE TITLE
Default "SnapRAID.config" depriciated (bug or feature?)

### ISSUE THREAD

**Issue by Frederic-LM** [Smurf-IV/Elucidate#69]
Setting to control SnapRAID write down a "SnapRAID.config" file.
but SnapRAID use a snapraid.conf file.

**Comment by Smurf-IV** [comment]
The name does not matter, as it is run with the setting to explictly tell SnapRaid where and what the config file is

**Comment by Frederic-LM** [comment]
Agreed , but  if you want to use snap raid command line to troubleshoot an issue (as I did when cf my other report)
then Snap Raid will tell you that there is no config file (in a less verbose way).
Of course it's just the matter of renaming the file .. for snap raid to be able to find it..  then tell Elucidate to use the renamed file.

it really is not a big issue, but i would make sens if both were using the same file name (and it would not take long to "fix")

**Comment by Smurf-IV** [comment]
Done as part of #68
