### ISSUE TITLE
Multiple configurations?

### ISSUE THREAD

**Issue by jenny787** [Smurf-IV/Elucidate#71]
I have multiple pools of disks (drivepool).  Could I request a way to switch between configs in elcuidate?  I can create a separate config/settings file for snapraid....but then if there's some way to manage it in elucidate, that would be great.

**Comment by Smurf-IV** [comment]
A "Switching" operation would require you to click in a few places.
But, there is already a way to do this (Just not obvious)
- Just go to the settings and select the other snapRaid.conf file and hit save.

**Comment by jenny787** [comment]
Yes!  I just realized this last night.  Pretty easy lol.
THis is not elucidate question, but I'm assuming with the other helpers/runners, I'll be able to create automation/schedulers for separate snapraid configs.

**Comment by Smurf-IV** [comment]
> Yes! I just realized this last night. Pretty easy lol.

:-)

> THis is not elucidate question, but I'm assuming with the other helpers/runners, I'll be able to create automation/schedulers for separate snapraid configs.

If you use the SnapRiad command line directly then yes .. (From memory  `Snapraid.exe -c "Location of config file" command`)
