### ISSUE TITLE
Request for Simon Coghlan

### ISSUE THREAD

**Issue by markfilipak-windows** [Smurf-IV/Elucidate#73]
Hi Simon,

Sorry to post here, but I could find no other way to contact you. Would you kindly notify me when you have binaries that can be downloaded and auditioned. I'd like to take Elucidate out for a test drive.

Regards,
Mark Filipak.
![markfilipak](https://user-images.githubusercontent.com/45295408/103744952-a24fe600-4fcc-11eb-9b33-41530a5227a1.jpg)

**Comment by Smurf-IV** [comment]
Just go to the releases as per normal github projects:

https://github.com/Smurf-IV/Elucidate/releases
