### ISSUE TITLE
Unable to use 128 block size

### ISSUE THREAD

**Issue by DataWhig** [Smurf-IV/Elucidate#74]
Have been using Elucidate 15.x with 128 block size, had tried newer versions but had issues reading config. Tried latest and still issue reading config so decided to add changes paragraph by paragraph and see what issue was, turns out it works fine until I try and use 128KB block size as the minimum is now 256. Is there a reason this is now minimum?

**Comment by Smurf-IV** [comment]
Thanks for the report.. I was not aware of that minimum being that value.

**Comment by Smurf-IV** [comment]
The docs state that the default is 256:
https://www.snapraid.it/manual#7.8

And it should be able to go down to 64:
https://sourceforge.net/p/snapraid/discussion/1677233/thread/927d6038/#c1f6

**Comment by Smurf-IV** [comment]
Released here:
https://github.com/Smurf-IV/Elucidate/releases/tag/2021.4.4
