### ISSUE TITLE
Provide checksums for the files! So that I can verify the authenticity of the files, thanks

### ISSUE THREAD

**Issue by ccchan234** [Smurf-IV/Elucidate#75]
seems hard for a signed .exe for windows as it cost some money.

how about providing the checksums like sha256 on github?

it's not ideal as someone who hacked the server can change both the file and the checksum,
but it's better than nothing.

thanks.

**Comment by Smurf-IV** [comment]
https://www.shellhacks.com/windows-md5-sha256-checksum-built-in-utility/

``` cmd
CertUtil -hashfile "Elucidate.Windows.Installer 2021.4.1030.4.zip" SHA256
SHA256 hash of Elucidate.Windows.Installer 2021.4.1030.4.zip:
db7f2d0920cf92e276f14340ece3439562e174d8a417bcfe8cc7e1e0cbf5665d
CertUtil: -hashfile command completed successfully.
```
