### ISSUE TITLE
Problem with fix command

### ISSUE THREAD

**Issue by waxweazle2001** [Smurf-IV/Elucidate#81]
I Changed my HDD in the Server and wanted it to fix the lost files.
I did a full sync before, But in snapraid gui when i give it the command "-d dx fix" (where "x" is the name of the new drive) and run the "fix" button i get an error message. 
I did now the same without the gui and it worked fine without any failure. Could the default command "-e" the cause that it don't run with the extended parameters in the gui?

**Comment by Smurf-IV** [comment]
Can you attach the Log file that was generated please (%ProgrmData\Elucidate\Logs\...)
And to override the default parameters you should have used the `+` symbol as described the help

**Comment by waxweazle2001** [comment]
Ok, So if I do the sync with the Command "+-d d2" then it runs, Ok I don't read the Manual before because, when i did it the last time it runs without it. THX for the Help.
