### ISSUE TITLE
[bug] Scrub run with default caused an error

### ISSUE THREAD

**Issue by NIBAOBAOZHALE** [Smurf-IV/Elucidate#82]
This is the log：
![image](https://user-images.githubusercontent.com/17777437/147648242-2fe19283-d859-4920-a4cf-7e7a822e4ac3.png)

snapraid version is 11.3
Elucidate release is latest

**Comment by Smurf-IV** [comment]
That `-N` gets set (in that position) when the following is true@
`if (Properties.Settings.Default.FindByNameInSync)`

So to work around that, just unset the checkbox in "Settings" and save:
![image](https://user-images.githubusercontent.com/2418812/147649906-8587b02d-2e6a-4a0a-946e-0cd6f7dfb2f6.png)

**Comment by NIBAOBAOZHALE** [comment]
THX for reply！
it works👏

**Comment by Smurf-IV** [comment]
I'm fixing this so that it applies to the relevant commands only (As per documentation !)

**Comment by Smurf-IV** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/2418812/147674000-5f735b25-bbd9-4eb6-8324-a9de42b1b0d6.png)

**Comment by Smurf-IV** [comment]
@NIBAOBAOZHALE Please can you test the setting with the build please:
https://github.com/Smurf-IV/Elucidate/releases/tag/V2021.12.29

**Comment by NIBAOBAOZHALE** [comment]
> @NIBAOBAOZHALE Please can you test the setting with the build please: https://github.com/Smurf-IV/Elucidate/releases/tag/V2021.12.29

it's works fine！THX
