### ISSUE TITLE
Problem with the Percentage display

### ISSUE THREAD

**Issue by waxweazle2001** [Smurf-IV/Elucidate#94]
Hello Smurf-IV,

Since I updated my Server I saw that at about 90TB of Data the percentage display is beginning with 0%, but the Bytes are written permanently like it should. But it is a little confusing when u do a complete sync and the display runs again at 0% within.

**Comment by Smurf-IV** [comment]
Can you give a screen shot of what you are experiencing?
And also the version of the OS, SnapRaid, Elucidate - Thanks

Note: I run this on 130TB, so not sure what you are experiencing.

**Comment by waxweazle2001** [comment]
Hello,

I run a Win 10 22H2 (Build 19045.3570) with Snapraid 11.5 and the Newest Elucidate 2022,12.20.26.

I can't make a Screenshot because i don't write a Log with the Full Sync. I put some Data on my Server and try a normal sync with log to see if it happens there again.
If not I must do the Full Sync which takes about 4 Days, so I must do it over the Weekend and I only can give u a log or something when its done.

**Comment by waxweazle2001** [comment]
I have made a normal Sync with log, but in the Log are no percentages showed, so i can't see if the percentage was fallen to 0% and started new.
And because the Window which shows the progress is limited and goes on and on, it's difficult to catch the right moment to take the Screenshot. I can't look at it all night long for days. ;-)
Is it possible to catch the Percentage in the Log so i can do a Full Sync with log an check it afterwards?

**Comment by Smurf-IV** [comment]
- if you have set the log option, in the settings, then all logging will go into that.
- The percentage is retrieved from the SnapRaid console output
- Are you sure it's not just stuck in the initial processing stage (i.e. reading files in to determine changes) before actually starting the Raid steps ?

**Comment by waxweazle2001** [comment]
1) Which Option is that? Verbose Log and Debugg or only Verbose?
2) In the "Log History" I can only check the "Log with Errors"-Box, because the other Boxes are hidden from the frame unter the options and can't be moved more down.
3) No the Initial process is done, how i said, the sync runs without any failures shown, but the percentage is resetted to 0% at about 87%, can't say if it is the same point every time. Because of this i need to make a Log with the Percentage to see.
It only seems to be an display failure or something but can't say it for sure.

**Comment by Smurf-IV** [comment]
When `SnapRaid` is performing syncing during Startup etc, then it is not showing any progress,
Then Elucidate will go into "Marque" mode:
![RunningProgress](https://github.com/Smurf-IV/Elucidate/assets/2418812/ddefdcf5-9b1b-4b77-aedc-ff075638006b)

Once `SnapRaid` starts to out put progress, then Elucidate will detect that and start to show progress:
(It will be the last line in the Log)
![RunningProgressValues](https://github.com/Smurf-IV/Elucidate/assets/2418812/02fd299c-bf93-4bd4-bf42-9ec553cba09e)

The setting that is supposed to track the log output is this (But when it is off there is a problem, i've just noticed !!)
![image](https://github.com/Smurf-IV/Elucidate/assets/2418812/471672d3-2bd2-453e-97c6-4f5c736ddabb)

**Comment by waxweazle2001** [comment]
I got "Display Output" Checked and get the Output, but in the Log I write the percentage is not logged with. Only the progress from the sync. The Percentage will only be Displayed in the Output Window from the GUI.
But the failure seems only to be when I do a full scan, but I can't be at Home for 4 Days and check in the Night or when it happens to make a screenshot of it. At one Point the Logged Infos on the Window in the GUI are disappeared and because of the ongoing process I can't scroll to the Point and make a screenshot. This is the Problem. Because of this I asked for a possibility to log the percentage in the logfile.

**Comment by Smurf-IV** [comment]
> I got "Display Output" Checked and get the Output

Good, That means that the logging will be going to a location like this.
Anything that is displayed in the log window should be stored in a "Rolling" file, that it is limited to 1024 MB's
![image](https://github.com/Smurf-IV/Elucidate/assets/2418812/187243d4-ea24-4087-b9ed-10739ab03c8d)

**Comment by waxweazle2001** [comment]
So i checked the Logs and find the Point when the Percentage flips. Here is the Screenshot of it. But it only seems to be when i do a full sync. The Log strangely enough stopps then at 8% and there is nothing written the sync was successful, but in the GUI the sync is successful. Don't know what's right then.

![Prozentfehler Snapraid GUI](https://github.com/Smurf-IV/Elucidate/assets/22542230/15a062c4-51ec-4cc9-9a97-f024e504bfc3)

**Comment by Smurf-IV** [comment]
Hmm..
Those are the line being reported by SnapRaid, So the GUI has "NO Chance" of knowing anything different.
So that needs reporting to the SnapRaid forum (With the version in use etc)
As for the Success state, that's because SnapRiad has returned an runtime code of '0' thus again the Gui has to assume success.

**Comment by waxweazle2001** [comment]
Oh ok, then I would update to the newest Version of Snapraid, Don't Update that very much and when nexttime do a full Sync I will see what's happening. Eventually it's a bug in the 11.5 Version of Snapraid or with any Update on Windows and this Version of Snapraid.
