### ISSUE TITLE
Error renaming the content file (Input/Output Error [5/123])

### ISSUE THREAD

**Issue by waxweazle2001** [Smurf-IV/Elucidate#97]
Hello Smurf-IV,

as the long time passes through I wanted to do a Full Sync again but I got this Error when starting the sync, after the Verifiing of the HDDs.

"2023-12-28 18:09:41.9471 [19]  WARN: Elucidate.Controls.RunControl: Unexpected Windows error 123. 
2023-12-28 18:09:41.9471 [19]  WARN: Elucidate.Controls.RunControl: Error renaming the content file 'F:/.tmp' to 'F:/' in rename(). Input/output error [5/123]. "

I delete the old content Files, because the new snapraid Version (12.2) don't recognize the content Files anymore. Because of that i wanted to do a Full Sync.

Do you have an Idea on this Error?

Greetings 

Wax

**Comment by waxweazle2001** [comment]
I found the solution myself, in the new snapraid Version you must specify the name of the content-file, which was not neccesary in the old Version.
After specifying the name of the content File the Sync worked well.

**Comment by Smurf-IV** [comment]
Thanks for the update.
Note:
- Those messages come from SnapRaid not Elucidate
- I have not come across a problem with the -F option (I did it last at beginning December '23)
